---
version: '{build}'
shallow_clone: true
environment:
  global:
    AUTH_TOKEN:
      secure: lvmCYHLJhYc+Thwtr0lC/K97WI54apWQTU3Eks+BXpbDrKGkYGYYWebpF44ji1Ue
    VIMVER: 80
  matrix:
  - COMPILER: msvc
    CPU: i386
    ENV: /x86
    BIT: 32
  - COMPILER: msvc
    CPU: AMD64
    ENV: /x64
    BIT: 64
  - COMPILER: cygwin
  #- COMPILER: mingw
  #  BIT: 32
  - COMPILER: msys2
    MSYS2_ARCH: i686
    MSYS2_DIR: msys64
    MSYSTEM: MINGW32
    BIT: 32
  - COMPILER: msys2
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64
build_script:
  - '%APPVEYOR_BUILD_FOLDER%\tools\appveyor.bat'
test_script:
  - '%APPVEYOR_BUILD_FOLDER%\tools\appveyor.bat test'
artifacts:
  - path: lib/vimproc_*.dll
    name: vimproc.dll
deploy:
  provider: GitHub
  description: vimproc
  auth_token:
    secure: lvmCYHLJhYc+Thwtr0lC/K97WI54apWQTU3Eks+BXpbDrKGkYGYYWebpF44ji1Ue
  on:
    appveyor_repo_tag: true
    COMPILER: msvc
